name: Build Docker Image

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: window-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t your-docker-image-name:latest .

    - name: Show Docker images
      run: docker images

